### ISSUE TITLE
i*m*plementation not bolded correctly

### ISSUE THREAD

**Issue by dfenjves** [learn-co-curriculum/ios-your-first-NSLog#3]
this is the "i*m*plementation" file for the FISAppDelegate class - Bolding incorrect

**Comment by markedwardmurray** [comment]
@kvignali @matbalez 

Daniel's pointing out that Learn isn't handling markdown correctly, or at least not in a similar way to Github. In another reading, I have noticed that a table containing the logical operator `||` doesn't display correctly.

**Comment by matbalez** [comment]
Kaitlin, could you please log a Learn issue and deprecate this one?

**Comment by markedwardmurray** [comment]
I think it's because the double-star bolding syntax is within a list

**Comment by markedwardmurray** [comment]
Actually I think it's just because the bolding is in the middle of a word. Same thing happens on another word in the Intro To Xcode reading too.

**Comment by markedwardmurray** [comment]
closing this as an issue on the repo
