### ISSUE TITLE
light doesn't come up

### ISSUE THREAD

**Issue by hkxnyc** [learn-co-curriculum/ios-your-first-NSLog#4]
I wanted to know if it is bug or it always takes long time to get the lights on after finishing one since it always take me long time to move on to the next because of the lights.  Currently, I am stuck on "Your First NSLog" lab, and waiting for pull request light to come up.
Please advise.

**Comment by markedwardmurray** [comment]
Please ask questions in learn for technical issues not related to problems with the content. I noticed that you opened a PR on this repository which is not the repository that you should have forked for the assignment. You need to open the PR on your fork of the `learn-co-students` repo for the batch you're in (`000`). This is your fork  https://github.com/hkxnyc/ios-your-first-NSLog-000 

Opening a PR from your fork should get the green light to turn on.
