### ISSUE TITLE
Your first NSLog not complete

### ISSUE THREAD

**Issue by dominicprescod** [learn-co-curriculum/ios-your-first-NSLog#6]
I finished this lab and for some reason its not marked as complete.

**Comment by markedwardmurray** [comment]
Hi Dominic, would you use the Ask A Question feature in Learn? We can get you some help on this a little easier through that interface.

**Comment by dominicprescod** [comment]
Sure, I did. I thought this was a website glitch
[image: Screen Shot 2015-11-03 at 1.08.16 PM.png]
On Tue, Nov 3, 2015 at 9:36 AM Mark E Murray <notifications@github.com>
wrote:

> Hi Dominic, would you use the Ask A Question feature in Learn? We can get
> you some help on this a little easier through that interface.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/learn-co-curriculum/ios-your-first-NSLog/issues/6#issuecomment-153373589>
> .
>
-- 
Regards,

Dominic Prescod
347.475.2528

**Comment by markedwardmurray** [comment]
Ah, yes, there are several channels for reporting problems. The "Raise An Issue" is typically reserved for content issues with the readings and labs. The "Ask A Question" button is for getting help with the students experience, which includes setup problems. The "Report A Bug" button is for technical problems with the website.

If the Local Build light for your lessons is failing to come on, it's most likely an issue with your setup (environment setup is tricky to automate). The chat feature available through "Ask A Question" is the easiest way for us to diagnose the problem you're experiencing.

**Comment by dominicprescod** [comment]
Ok  understood, ill wait for a response. Thank you
Dom

On Tue, Nov 3, 2015 at 1:24 PM Mark E Murray <notifications@github.com>
wrote:

> Ah, yes, there are several channels for reporting problems. The "Raise An
> Issue" is typically reserved for content issues with the readings and labs.
> The "Ask A Question" button is for getting help with the students
> experience, which includes setup problems. The "Report A Bug" button is for
> technical problems with the website.
>
> If the Local Build light for your lessons is failing to come on, it's most
> likely an issue with your setup (environment setup is tricky to automate).
> The chat feature available through "Ask A Question" is the easiest way for
> us to diagnose the problem you're experiencing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/learn-co-curriculum/ios-your-first-NSLog/issues/6#issuecomment-153445217>
> .
>
-- 
Regards,

Dominic Prescod
347.475.2528

**Comment by markedwardmurray** [comment]
Have you opened a new question thread? I haven't gotten a ping about one from your username yet today.

**Comment by dominicprescod** [comment]
Strange. I did right before I sent the last email. Maybe its a bit
delayed?[image:
Screen Shot 2015-11-03 at 1.44.01 PM.png]


On Tue, Nov 3, 2015 at 1:41 PM Mark E Murray <notifications@github.com>
wrote:

> Have you opened a new question thread? I haven't gotten a ping about one
> from your username yet today.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/learn-co-curriculum/ios-your-first-NSLog/issues/6#issuecomment-153449533>
> .
>
-- 
Regards,

Dominic Prescod
347.475.2528

**Comment by dominicprescod** [comment]
Also side question to ask you as i'm chatting with you now. I started
reading "C Programming for Absolute Beginners" earlier this year and i'm
almost finished with the book. Is there any merit to completing it?

I'm noticing a lot of referencing to the C language as I progress on
Learn.co



On Tue, Nov 3, 2015 at 1:45 PM Dominic Prescod <dominicprescod@gmail.com>
wrote:

> Strange. I did right before I sent the last email. Maybe its a bit delayed?[image:
> Screen Shot 2015-11-03 at 1.44.01 PM.png]
>
>
> On Tue, Nov 3, 2015 at 1:41 PM Mark E Murray <notifications@github.com>
> wrote:
>
>> Have you opened a new question thread? I haven't gotten a ping about one
>> from your username yet today.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/learn-co-curriculum/ios-your-first-NSLog/issues/6#issuecomment-153449533>
>> .
>>
> --
> Regards,
>
> Dominic Prescod
> 347.475.2528

-- 
Regards,

Dominic Prescod
347.475.2528

**Comment by markedwardmurray** [comment]
Hm, that's weird. I didn't get a ping and I can't see an open question from you in the interface. Would you mind trying it again? If it still doesn't work I'll have you report this as a bug.

**Comment by markedwardmurray** [comment]
I don't have experience with that work. Knowledge of C is helpful for learning Objective-C but isn't strictly necessary. Objective-C is essentially an extension of the C language (instead of overriding it like other C-family languages like Ruby, Python, and Swift) so everything in C is available to programming in Objective-C.

**Comment by dominicprescod** [comment]
just did again..let me know if you see it

On Tue, Nov 3, 2015 at 1:50 PM Mark E Murray <notifications@github.com>
wrote:

> Hm, that's weird. I didn't get a ping and I can't see an open question
> from you in the interface. Would you mind trying it again? If it still
> doesn't work I'll have you report this as a bug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/learn-co-curriculum/ios-your-first-NSLog/issues/6#issuecomment-153451939>
> .
>
-- 
Regards,

Dominic Prescod
347.475.2528

**Comment by markedwardmurray** [comment]
As for outside resources, we used to recommend http://www.amazon.com/Learning-iOS-Development-Hands-Fundamentals/dp/0321862961 but this version is outdated now. I'm also a fan of Matt Neuberg's books http://www.amazon.com/Programming-iOS-Views-Controllers-Frameworks/dp/1491908734 . Everything going forward from iOS 9.0 is heavy on Swift though.

**Comment by dominicprescod** [comment]
Got it..ill think press on with the book..sounds like it won't hurt to know
more about it. Thanks

On Tue, Nov 3, 2015 at 1:51 PM Mark E Murray <notifications@github.com>
wrote:

> I don't have experience with that work. Knowledge of C is helpful for
> learning Objective-C but isn't strictly necessary. Objective-C is
> essentially an extension of the C language (instead of overriding it like
> other C-family languages like Ruby, Python, and Swift) so everything in C
> is available to programming in Objective-C.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/learn-co-curriculum/ios-your-first-NSLog/issues/6#issuecomment-153452296>
> .
>
-- 
Regards,

Dominic Prescod
347.475.2528
